### ISSUE TITLE
User Profile: Draft Stories

### ISSUE THREAD

**Issue by cylau1031** [parallel-stories/capstone#157]
user story: adding more scenes to story after publishing and leaving writing space

**Comment by cylau1031** [comment]
links in user profile to draft stories

**Comment by rkaur01** [comment]
1. Check if uid on card is same as user logged in, otherwise, send 404 Not Found. We can't allow other users to edit someone else's work.

2. Draft Routes
      -if unpublished (/write/:cardId) loop thru user/unpublishedCards on firebase
      -if published (/write/continue/:storyBranch) loop thru user/storyBranch on firebase
